#use wml::debian::translation-check translation="1.1" mindelta="1"
<define-tag description>sikkerhedsopdatering</define-tag>
<define-tag moreinfo>
<p>Flere sårbarheder blev opdaget i Django, et webudviklingsframework til Python 
på højt niveau.  Projektet Common Vulnerabilities and Exposures har registreret 
følgende problemer:</p>

<ul>

<li><a href="https://security-tracker.debian.org/tracker/CVE-2016-9013">CVE-2016-9013</a>

    <p>Marti Raudsepp rapporterede at en bruger med en hårdkodet adgangskode, 
    blev oprettet når der blev afviklet tests med en Oracle-database.</p></li>

<li><a href="https://security-tracker.debian.org/tracker/CVE-2016-9014">CVE-2016-9014</a>

    <p>Aymeric Augustin opdagede at Django ikke på korrekt vis validerede 
    Host-headeren mod settings.ALLOWED_HOSTS, når debugindstillingen er 
    aktiveret.  En fjernangriber kunne drage nytte af fejlen til at iværksætte 
    DNS-rebinding-angreb.</p></li>

<li><a href="https://security-tracker.debian.org/tracker/CVE-2017-7233">CVE-2017-7233</a>

    <p>Man opdagede at is_safe_url() ikke på korrekt vis håndterede visse 
    numeriske URL'er som sikre.  En fjernangriber kunne drage nytte af fejlen 
    til at iværksætte XSS-angreb eller til at anvende en Django-server som en 
    åben viderestilling.</p></li>

<li><a href="https://security-tracker.debian.org/tracker/CVE-2017-7234">CVE-2017-7234</a>

    <p>Phithon fra Chaitin Tech opdagede en åben viderestilling-sårbarhed i 
    view'et django.views.static.serve().  Bemærk at dette view ikke er beregnet 
    til anvendelse i produktion.</p></li>

</ul>

<p>I den stabile distribution (jessie), er disse problemer rettet i
version 1.7.11-1+deb8u2.</p>

<p>Vi anbefaler at du opgraderer dine python-django-pakker.</p>
</define-tag>

# do not modify the following line
#include "$(ENGLISHDIR)/security/2017/dsa-3835.data"
