#use wml::debian::translation-check translation="1.4" maintainer="Lev Lamberov"
<define-tag description>обновление безопасности LTS</define-tag>
<define-tag moreinfo>
<p>В обновлении DLA-25-1 для python2.6 была обнаружена регрессия,
которая может приводить к тому, что приложения на языке Python прерываются в том случае, если они работают во время
выполнения обновления, но ещё не импортировали модуль 'os', то же самое происходит и после
выполнения обновления. Данное обновление исправляет этот сценарий обновления.</p>

<p>Ниже приводится изначальный текст рекомендации.</p>

<p>В python2.6 были обнаружены многочисленные уязвимости. Наиболее
важны из них следующие:</p>

<ul>

<li><a href="https://security-tracker.debian.org/tracker/CVE-2013-4238">CVE-2013-4238</a>

    <p>Некорректная обработка NUL-байтов в сертификатах имён узлов может позволить
    выполнять подделку сервера с помощью специально сформированных сертификатов, подписанных
    доверенным авторитетом.</p></li>

<li><a href="https://security-tracker.debian.org/tracker/CVE-2014-1912">CVE-2014-1912</a>

    <p>Переполнение буфера в socket.recvfrom_into, приводящее к аварийной остановке
    приложения и возможному выполнению кода.</p></li>

</ul>

<p>В Debian 6 <q>Squeeze</q> эти проблемы были исправлены в пакете python2.6 версии 2.6.6-8+deb6u2</p>
</define-tag>

# do not modify the following line
#include "$(ENGLISHDIR)/security/2014/dla-25.data"
# $Id$
