#use wml::debian::translation-check translation="1.1"
<define-tag description>actualización de seguridad</define-tag>
<define-tag moreinfo>
<p>James Davis descubrió dos problemas en Django, una infraestructura de soporte de desarrollo web
Python de alto nivel, que puede dar lugar a un ataque de denegación de servicio.
Un atacante con control sobre la entrada de la función
django.utils.html.urlize() o de los métodos chars() y words() de django.utils.text.Truncator
podría manipular una cadena de caracteres de forma tal que la ejecución de la aplicación se bloqueara.</p>

<p>Para la distribución «antigua estable» (jessie), estos problemas se han corregido
en la versión 1.7.11-1+deb8u3.</p>

<p>Para la distribución «estable» (stretch), estos problemas se han corregido en
la versión 1:1.10.7-2+deb9u1.</p>

<p>Le recomendamos que actualice los paquetes de python-django.</p>

<p>Para información detallada sobre el estado de seguridad de python-django consulte
su página del «security tracker» en:
<a href="https://security-tracker.debian.org/tracker/python-django">\
https://security-tracker.debian.org/tracker/python-django</a></p>
</define-tag>

# do not modify the following line
#include "$(ENGLISHDIR)/security/2018/dsa-4161.data"
