<define-tag description>security update</define-tag>
<define-tag moreinfo>
<p>James Davis discovered two issues in Django, a high-level Python web
development framework, that can lead to a denial-of-service attack.
An attacker with control on the input of the django.utils.html.urlize()
function or django.utils.text.Truncator's chars() and words() methods
could craft a string that might stuck the execution of the application.</p>

<p>For the oldstable distribution (jessie), these problems have been fixed
in version 1.7.11-1+deb8u3.</p>

<p>For the stable distribution (stretch), these problems have been fixed in
version 1:1.10.7-2+deb9u1.</p>

<p>We recommend that you upgrade your python-django packages.</p>

<p>For the detailed security status of python-django please refer to
its security tracker page at:
<a href="https://security-tracker.debian.org/tracker/python-django">\
https://security-tracker.debian.org/tracker/python-django</a></p>
</define-tag>

# do not modify the following line
#include "$(ENGLISHDIR)/security/2018/dsa-4161.data"
# $Id$
