<define-tag description>バッファオーバーフロー</define-tag>
<define-tag moreinfo>
<p>
Sebastian Schmidt さんにより、Python の getaddrinfo 関数にバッファオーバ
フローバグが発見されました。この欠陥は、リモートの攻撃者が DNS
経由で提供した IPv6 アドレスが、
スタック上のメモリを上書きしてしまうというものです。</p>

<p>
このバグは、python 2.2 と 2.2.1 にのみ存在し、IPv6 
サポートが有効になっている時のみに問題になります。Debian woody の
python2.2 パッケージはこの条件に当てはまります
(「python」パッケージは当てはまりません)。</p>

<p>安定版 (stable) ディストリビューション (woody) では、この問題はバージョン
2.2.1-4.3 で修正されています。</p>

<p>不安定版 (unstable) ディストリビューション (sid) 
には、この問題はありません。</p>

<p>直ちに python2.2 パッケージをアップグレードすることをお勧めします。</p>
</define-tag>

#use wml::debian::translation-check translation="1.2"
# do not modify the following line
#include "$(ENGLISHDIR)/security/2004/dsa-458.data"
# $Id$
